linters:
  enable:
    # Default linters plus these:
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - gomnd
    - gosec
    - ireturn
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - revive
    - unconvert
    - unparam

issues:
  include:
    # Re-enable revive's doc comment linters:
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
  exclude-rules:
    # Pipes are best used as pre-compiled globals, much like regexp.Mustcompile()
    - text: ".*Pipe is a global variable"
      linters:
        - gochecknoglobals
    # Reflection is slow, so some global reflect types are ok
    - text: ".*Type is a global variable"
      source: ".*Type = reflect.TypeOf\\(.*"
      linters:
        - gochecknoglobals
    # False positive for paralleltest usage detection
    - text: "Range statement for test Test.* does not use range value in test Run"
      linters:
        - paralleltest

linters-settings:
  ireturn:
    allow:
      # Defaults:
      - anon
      - error
      - empty
      - stdlib
      # Also allow these common interfaces:
      - github\.com\/go-git\/go-billy\/v5
      - golang\.org\/x\/tools\/godoc\/vfs
