linters:
  enable:
    # Default linters plus these:
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocognit
    - gocritic
    - gofmt
    - revive

issues:
  include:
    # Re-enable revive's doc comment linters:
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
  exclude-rules:
    # Pipes are best used as pre-compiled globals, much like regexp.Mustcompile()
    - text: ".*Pipe is a global variable"
      linters:
        - gochecknoglobals
    # Reflection is slow, so some global reflect types are ok
    - text: ".*Type is a global variable"
      source: ".*Type = reflect.TypeOf\\(.*"
      linters:
        - gochecknoglobals
