linters:
  enable:
    # Default linters plus these:
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gocognit
    - revive

issues:
  include:
    # Re-enable revive's doc comment linters:
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
