version: "2"
output:
  formats: 
    text:
      path: stdout
      color: true
linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gosec
    - ireturn
    - makezero
    - misspell
    - mnd
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - revive
    - unconvert
    - unparam
  settings:
    ireturn:
      allow:
        - anon
        - error
        - empty
        - generic
        - stdlib
        - github\.com\/go-git\/go-billy\/v5
        - golang\.org\/x\/tools\/godoc\/vfs
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
        text: .*Pipe is a global variable
      - linters:
          - gochecknoglobals
        text: .*Type is a global variable
        source: .*Type *= *reflect.TypeOf\(.*
      - linters:
          - paralleltest
        text: Range statement for test Test.* does not use range value in test Run
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
